drop table if exists bookmind_access_level cascade;
drop table if exists bookmind_book cascade;
drop table if exists bookmind_user cascade;
drop table if exists bookmind_one_time_code cascade;
drop table if exists bookmind_shelf cascade;
drop table if exists bookmind_shelf_action cascade;
drop table if exists bookmind_shelf_books cascade;
drop table if exists bookmind_user_authorities cascade;

create table bookmind_user
(
    id       bigint generated by default as identity primary key,
    version  bigint  default 0 not null,
    email    varchar(255) not null,
    enabled  boolean default false not null,
    password varchar(255) not null,
    username varchar(255) unique
);

create table bookmind_book
(
    id      bigint generated by default as identity primary key,
    version bigint default 0,
    author  varchar(255),
    title   varchar(255)
);

create table bookmind_shelf
(
    id      bigint generated by default as identity primary key,
    version bigint default 0,
    name    varchar(255),
    user_id bigint,
    foreign key (user_id) references bookmind_user (id)
);

create table bookmind_shelf_action
(
    id                bigint generated by default as identity primary key,
    version           bigint default 0,
    action_date       timestamp,
    shelf_action_type integer,
    book_id           bigint,
    shelf_id          bigint,
    foreign key (book_id) references bookmind_book (id) on delete cascade,
    foreign key (shelf_id) references bookmind_shelf (id) on delete cascade
);

create table bookmind_access_level
(
    id        bigint generated by default as identity primary key,
    version   bigint default 0,
    authority varchar(255)
);

create table bookmind_one_time_code
(
    id              bigint generated by default as identity primary key,
    version         bigint default 0,
    code            varchar(255) unique,
    expiration_date timestamp,
    user_id         bigint,
    foreign key (user_id) references bookmind_user (id) on delete cascade
);

create table bookmind_shelf_books
(
    shelf_id bigint not null,
    books_id bigint not null,
    primary key (shelf_id, books_id),
    foreign key (shelf_id) references bookmind_shelf (id) on delete cascade,
    foreign key (books_id) references bookmind_book (id) on delete cascade
);

create table bookmind_user_authorities
(
    user_id        bigint not null,
    authorities_id bigint not null,
    primary key (user_id, authorities_id),
    foreign key (user_id) references bookmind_user (id) on delete cascade,
    foreign key (authorities_id) references bookmind_access_level (id)
);

alter table bookmind_access_level
    owner to bookmind_admin;
alter table bookmind_book
    owner to bookmind_admin;
alter table bookmind_user
    owner to bookmind_admin;
alter table bookmind_one_time_code
    owner to bookmind_admin;
alter table bookmind_shelf
    owner to bookmind_admin;
alter table bookmind_shelf_action
    owner to bookmind_admin;
alter table bookmind_shelf_books
    owner to bookmind_admin;
alter table bookmind_user_authorities
    owner to bookmind_admin;

